#!/usr/bin/env python

import sys
import os
from subprocess import call
from mistansible import __path__ as mist_ansible_path

modules_path = os.path.join(mist_ansible_path[0], 'mist.modules')

call(["ansible-playbook", "-M"] + [modules_path] + sys.argv[1:])